// <auto-generated />
namespace reportLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02_April_2020_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_April_2020_001));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020239550_02_April_2020_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
