// <auto-generated />
namespace reportLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first_log : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_log));
        
        string IMigrationMetadata.Id
        {
            get { return "202004012010357_first_log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
